server :
  port : 8080
  context-path : /cms

spring : 
  datasource : 
    url : jdbc:mysql://localhost:3306/cms
    username : wafer
    password : wafer
    driver-class-name : com.mysql.jdbc.Driver
    max-active : 20
    max-idle : 0
    min-idle : 0
    max-wait : 10000
    max-wait-millis : 31536000
  jpa : 
    database : MYSQL
    show-sql : false
    hibernate :
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      dialect : org.hibernate.dialect.MySQL5Dialect
logging : 
  level : 
    com : 
      wafer : INFO 
    org :
      hibernate : INFO
      springframework : 
       web : INFO
    root : INFO 
